In [60]:
import pandas as pd
import numpy as np


In [61]:
data=pd.read_csv('/content/email.csv')

In [62]:
df=pd.DataFrame(data)

In [63]:
print(df)

            Category                                            Message
0                ham  Go until jurong point, crazy.. Available only ...
1                ham                      Ok lar... Joking wif u oni...
2               spam  Free entry in 2 a wkly comp to win FA Cup fina...
3                ham  U dun say so early hor... U c already then say...
4                ham  Nah I don't think he goes to usf, he lives aro...
...              ...                                                ...
5568             ham               Will ü b going to esplanade fr home?
5569             ham  Pity, * was in mood for that. So...any other s...
5570             ham  The guy did some bitching but I acted like i'd...
5571             ham                         Rofl. Its true to its name
5572  {"mode":"full"                                    isActive:false}

[5573 rows x 2 columns]


In [64]:
x=df.iloc[:,1].values
y=df.iloc[:,0].values


In [65]:
print(x)

['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
 'Ok lar... Joking wif u oni...'
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
 ...
 "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"
 'Rofl. Its true to its name' 'isActive:false}']


In [66]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [67]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [68]:
print(y)

[0 0 1 ... 0 0 2]


In [69]:
from sklearn.feature_extraction.text import CountVectorizer

In [70]:
cv=CountVectorizer(max_features=5000)
x=cv.fit_transform(x).toarray()

In [71]:
print(x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [72]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [73]:
from sklearn.naive_bayes import MultinomialNB
cls=MultinomialNB()
cls.fit(x_train,y_train)


MultinomialNB()

In [74]:
y_hat=cls.predict(x_test)

In [75]:
print(np.concatenate((y_hat.reshape(len(y_hat),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [76]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_hat))
print(accuracy_score(y_test,y_hat))

[[959   7]
 [  9 140]]
0.9856502242152466


In [77]:
email=[]
n=input('enter mail')
email.append(n)

enter mailhi hello


In [78]:
print(email)

['hi hello']


In [79]:
print(cls.predict(cv.transform(email)))

[0]
